export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const ADD_TO_DONATE = "ADD_TO_DONATE";
export const ADD_MULTIPLE_TO_DONATE = "ADD_MULTIPLE_TO_DONATE";
export const REMOVE_FROM_DONATE = "REMOVE_FROM_DONATE";
export const CLEAR_DONATE = "CLEAR_DONATE";
export const UPDATE_DONATE_QUANTITY = "UPDATE_DONATE_QUANTITY";
export const TOGGLE_DONATE = "TOGGLE_DONATE";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
